config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :members, only: [:index, :show, :edit ,:update] do
      resources :recruits, only: [:index]
    end
    resources :reports, only: [:index, :show, :update]
  end

  namespace :admin do
    resources :recruits, only: [:show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    root to: 'homes#top'
  end

  namespace :admin do

  end


  scope module: :public do
    resources :applies, only: [:show, :index, :update]
    get 'confirm' => 'applies#confirm'
    post 'confirm' => 'applies#confirm'
    get 'complete' => 'applies#complete'
  end

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about', as: 'about'
  end

  scope module: :public do
    get 'my_page' => 'members#show'
    get '/detail/:id' => 'members#detail', as: "member_detail"
    get 'information/edit' => 'members#edit'
    patch 'information/edit' => 'members#update'
    get 'unsubscribe' => 'members#unsubscribe'
    patch 'withdrawal' => 'members#withdrawal'

    post 'report/:member_id' => 'reports#create' , as: "report"
    get 'report/:member_id' => 'reports#new' , as: "report_page"
  end

  scope module: :public do
    resources :recruits, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
     resources :applies, only: [:new, :create]
     resources :post_comments, only: [:create]
     resource :good_recruits, only: [:create, :destroy]
    end
    #post 'check' => 'recruits#check'
    #get 'check' => 'recruits#check'
    get 'farvorite' => 'recruits#farvorite'
    get 'area' => 'recruits#area'
    get 'search' => 'recruits#search'
  end
  #募集要項作成ページ、一覧ページを作成するルーティングの設定


  scope module: :public do
    resources :notifications, only: :index
  end





  # 顧客用
# URL /customers/sign_in ...
devise_for :member, path: "customer", skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :good_recruits, dependent: :destroy

  has_many :post_comments, dependent: :destroy

  has_many :recruits, dependent: :destroy

  has_many :applies, dependent: :destroy

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy

  has_one_attached :profile_image

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :old, presence: true
  validates :telephone_number, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_user.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :show, :edit, :update]

  def index
    @members=Member.all
  end

  def show
    @member=Member.find(params[:id])
  end

  def edit
    @member=Member.find(params[:id])
  end

  def update
    member= Member.find(params[:id])
    member.update(member_params)
    redirect_to admin_member_path(member)
  end

  private

  def member_params
    params.require(:member).permit(:last_name, :first_name, :old, :birthday, :sex, :telephone_number, :email, :introduction, :is_deleted)
  end


end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/edit.html.erb
<h1>会員情報編集</h1>
<%= form_with model: @member,url: admin_member_path(@member),method: :patch do |f| %>

<p>氏名</p>
<%= f.text_field :last_name %> <%= f.text_field :first_name %>

<P>年齢</P>
<%= f.text_field :old %>

<p>生年月日</p>
<%= f.text_field :birthday %>

<p>性別</p>
<%= f.text_field :sex %>

<p>メールアドレス</p>
<%= f.text_field :email %>

<P>電話番号</P>
<%= f.text_field :telephone_number %>

<p>自己紹介</p>
<%= f.text_field :introduction %>

<p>プロフィール画像</p>
<%= f.file_field :profile_image, accept: "image/*" %>

<p>会員ステータス</p>
<p><%= f.radio_button :is_deleted, false %>有効</p>
<p><%= f.radio_button :is_deleted, true %>退会</p>
<%= f.submit '編集内容を保存',class: "btn btn-success" %>

<% end %>

app/views/admin/members/index.html.erb
<h2>会員一覧</h2>


<div class="container">
  <div class="row">
    <% @members.each do |member| %>
      <div class="col-lg-6">
        <div class="mr-auto">

          <div>
            <%= image_tag member.get_profile_image %>
          </div>

          <div>
            <p>会員ID</p>
            <%= member.id %>
          </div>

          <div>
            <p>会員名</p>
            <%= link_to admin_member_path(member) do %>
            <%= member.last_name + member.first_name %>
            <% end %>
          </div>

          <div>
            <p>メールアドレス</p>
            <%= member.email %>
          </div>

          <div>
            <p>電話番号</p>
            <%= member.telephone_number %>
          </div>

          <div>
            <p>退会ステータス</p>
            <% if member.is_deleted == false %>
              <p class="text-success">有効</p>
            <% else member.is_deleted == true %>
              <p class="text-secondary">退会</p>
            <% end %>
          </div>

          <div>
             <%= link_to admin_member_recruits_path(member) do %>
            <p><%= member.last_name + member.first_name %>の助っ人募集要項一覧</p>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/members/show.html.erb
<h1><%= @member.last_name + @member.first_name %>の会員詳細情報</h1>

<%= link_to edit_admin_member_path(@member) do %>
<p>編集する</p>
<% end %>

<%= image_tag @member.get_profile_image %>

<p>会員ID</p>
<%= @member.id %>

<p>会員名</p>
<%= @member.last_name + @member.first_name %>

<p>性別</p>
<%= @member.sex %>

<p>年齢</p>
<%= @member.old %>

<p>生年月日</p>
<%= @member.birthday %>

<p>メールアドレス</p>
<%= @member.email %>

<p>電話番号</p>
<%= @member.telephone_number %>

<p>会員ステータス</p>
      <% if @member.is_deleted == false %>
        有効
      <% else @member.is_deleted == true %>
        退会
      <% end %>