config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :members, only: [:index, :show, :edit ,:update] do
      resources :recruits, only: [:index]
    end
    resources :reports, only: [:index, :show, :update]
  end

  namespace :admin do
    resources :recruits, only: [:show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    root to: 'homes#top'
  end

  namespace :admin do

  end


  scope module: :public do
    resources :applies, only: [:show, :index, :update]
    get 'confirm' => 'applies#confirm'
    post 'confirm' => 'applies#confirm'
    get 'complete' => 'applies#complete'
  end

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about', as: 'about'
  end

  scope module: :public do
    get 'my_page' => 'members#show'
    get '/detail/:id' => 'members#detail', as: "member_detail"
    get 'information/edit' => 'members#edit'
    patch 'information/edit' => 'members#update'
    get 'unsubscribe' => 'members#unsubscribe'
    patch 'withdrawal' => 'members#withdrawal'

    post 'report/:member_id' => 'reports#create' , as: "report"
    get 'report/:member_id' => 'reports#new' , as: "report_page"
  end

  scope module: :public do
    resources :recruits, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
     resources :applies, only: [:new, :create]
     resources :post_comments, only: [:create]
     resource :good_recruits, only: [:create, :destroy]
    end
    #post 'check' => 'recruits#check'
    #get 'check' => 'recruits#check'
    get 'farvorite' => 'recruits#farvorite'
    get 'area' => 'recruits#area'
    get 'search' => 'recruits#search'
  end
  #募集要項作成ページ、一覧ページを作成するルーティングの設定


  scope module: :public do
    resources :notifications, only: :index
  end





  # 顧客用
# URL /customers/sign_in ...
devise_for :member, path: "customer", skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  has_many :good_recruits, dependent: :destroy

  has_many :post_comments, dependent: :destroy

  belongs_to :member

  has_many :applies, dependent: :destroy

  has_many :areas, dependent: :destroy

  has_many :notifications, dependent: :destroy, foreign_key: 'visited_id'

  enum area: {imperial_palace: 0, north: 1, east: 2, south: 3, west: 4 }

  has_one_attached :image

  validates :title, presence: true
  validates :team, presence: true
  validates :place, presence: true
  validates :day_and_time, presence: true
  validates :team_level, presence: true
  validates :content, presence: true


  def favorited_by?(member)
    good_recruits.exists?(member_id: member.id)
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [300, 300]).processed
  end


  def create_notification_post_comment!(current_member, post_comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = PostComment.select(:member_id).where(recruit_id: id).where.not(member_id: current_member.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_member, post_comment_id, temp_id['member_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_post_comment!(current_member, post_comment_id, member_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_member, post_comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_member.active_notifications.new(
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

end

app/controllers/admin/recruits_controller.rb
class Admin::RecruitsController < ApplicationController
  before_action :authenticate_admin!, only: [:index, :show, :destroy]

  def index
    @member = Member.find(params[:member_id])
    @recruits = @member.recruits
  end

  def show
    @recruit = Recruit.find(params[:id])
  end

  def destroy
    @recruit = Recruit.find(params[:id])
    @recruit.destroy
    redirect_to admin_root_path
  end
end

app/helpers/admin/recruits_helper.rb
module Admin::RecruitsHelper
end

app/views/admin/recruits/index.html.erb
<h1><%= @member.last_name + @member.first_name %>の募集要項一覧</h1>

<div class="container">
  <div class="row">
    <% @recruits.each do |recruit| %>
      <div class="col-lg-6">
        <div class="mr-auto">
          <div>
            <%= image_tag recruit.get_image %>
          </div>

          <div>
            <p>タイトル</p>
            <%= link_to admin_recruit_path(recruit) do %>
            <%= recruit.title %>
            <% end %>
          </div>

          <div>
            <p>チーム名</p>
            <%= recruit.team %>
          </div>

          <div>
            <p>主な活動エリア</p>
            <%= recruit.area_i18n %>
          </div>

          <div>
            <p>場所</p>
            <%= recruit.place %>
          </div>

          <div>
            <p>日時</p>
            <%= recruit.day_and_time %>
          </div>


          <div>
            <p><%= link_to "#{recruit.post_comments.count} コメント", admin_recruit_path(recruit.id) %></p>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/recruits/show.html.erb
<h1>募集要項詳細ページ</h1>

<div>
  <p>画像</p>
  <%= image_tag @recruit.get_image %>

  <p>タイトル</p>
  <%= @recruit.title %>

  <p>チーム名</p>
  <%= @recruit.team %>

  <p>場所</p>
  <%= @recruit.place %>

  <p>日時</p>
  <%= @recruit.day_and_time %>

  <p>チームレベル(1~10段階)</p>
  <%= @recruit.team_level %>

  <p>本文</p>
  <%= @recruit.content %>

  <p>代表者電話番号</p>
  <%= @recruit.member.telephone_number %>

  <p>代表者メールアドレス</p>
  <%= @recruit.member.email %>

  <p>代表者</p>
  <%= link_to admin_member_path(@recruit.member_id) do %>
  <%= @recruit.member.last_name + @recruit.member.first_name %>
  <% end %>

  <div>
    <p>コメント件数：<%= @recruit.post_comments.count %></p>
    <% @recruit.post_comments.each do |post_comment| %>
      <p><%= image_tag post_comment.member.get_profile_image %></p>

      <%= link_to member_detail_path(post_comment.member.id) do %>
      <p><%= post_comment.member.last_name + post_comment.member.first_name %></p>
      <% end %>

      <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>

      <%= link_to "削除", admin_recruit_post_comment_path(post_comment.recruit, post_comment), method: :delete %>

    <% end %>
  </div>

  <%= link_to "削除する", admin_recruit_path, method: :delete ,class: "btn btn-danger" %>
</div>