config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :members, only: [:index, :show, :edit ,:update] do
      resources :recruits, only: [:index]
    end
    resources :reports, only: [:index, :show, :update]
  end

  namespace :admin do
    resources :recruits, only: [:show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
  end

  namespace :admin do
    root to: 'homes#top'
  end

  namespace :admin do

  end


  scope module: :public do
    resources :applies, only: [:show, :index, :update]
    get 'confirm' => 'applies#confirm'
    post 'confirm' => 'applies#confirm'
    get 'complete' => 'applies#complete'
  end

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about', as: 'about'
  end

  scope module: :public do
    get 'my_page' => 'members#show'
    get '/detail/:id' => 'members#detail', as: "member_detail"
    get 'information/edit' => 'members#edit'
    patch 'information/edit' => 'members#update'
    get 'unsubscribe' => 'members#unsubscribe'
    patch 'withdrawal' => 'members#withdrawal'

    post 'report/:member_id' => 'reports#create' , as: "report"
    get 'report/:member_id' => 'reports#new' , as: "report_page"
  end

  scope module: :public do
    resources :recruits, only: [:new, :create, :destroy, :index, :show, :edit, :update] do
     resources :applies, only: [:new, :create]
     resources :post_comments, only: [:create]
     resource :good_recruits, only: [:create, :destroy]
    end
    #post 'check' => 'recruits#check'
    #get 'check' => 'recruits#check'
    get 'farvorite' => 'recruits#farvorite'
    get 'area' => 'recruits#area'
    get 'search' => 'recruits#search'
  end
  #募集要項作成ページ、一覧ページを作成するルーティングの設定


  scope module: :public do
    resources :notifications, only: :index
  end





  # 顧客用
# URL /customers/sign_in ...
devise_for :member, path: "customer", skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ALL STAR</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="mb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-dark py-3">
          <div class="container">
            <a class="navbar-brand" href="/">ALL STAR</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                    募集要項一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to admin_members_path, class: 'nav-link text-light' do %>
                    会員一覧
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to admin_reports_path, class: 'nav-link text-light' do %>
                    <p>通報一覧</p>
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                    ログアウト
                    <% end %>
                  </li>
                <% elsif member_signed_in? %>
                  <li class="nav-item">
                    <%= link_to my_page_path, class: 'nav-link text-light' do %>
                    myページ
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to recruits_path, class: 'nav-link text-light' do %>
                    助っ人募集要項
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_recruit_path, class: 'nav-link text-light' do %>
                    助っ人募集要項作成
                    <% end %>
                  </li>

                  <% if unchecked_notifications.any? %>
                    <i class="fa fa-circle" style="color: gold;"></i>
                  <% end %>
                  <li class="nav-item">
                    <%= link_to notifications_path, class: 'nav-link text-light' do %>
                    通知
                    <% end %>
                  </li>

                  <li class="nav-item">
                    <%= link_to destroy_member_session_path, method: :delete, class: 'nav-link text-light' do %>
                    ログアウト
                    <% end %>
                  </li>

                  <%= form_with url: search_path, local: true, method: :get do |form| %>
                  <%= form.text_field :keyword %>
                  <%= form.submit "検索" %>
                  <% end %>

                <% else %>
                  <li class="nav-item">
                    <%= link_to about_path, class: 'nav-link text-light' do %>
                    About
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to recruits_path, class: 'nav-link text-light' do %>
                    助っ人募集要項
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_member_registration_path, class: 'nav-link text-light' do %>
                    新規登録
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_member_session_path, class: 'nav-link text-light' do %>
                    ログイン
                    <% end %>
                  </li>

                  <!--キーワード検索機能-->
                  <%= form_with url: search_path, local: true, method: :get do |form| %>
                  <%= form.text_field :keyword %>
                  <%= form.submit "検索" %>
                  <% end %>
                <% end %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5 ">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>